apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: default
  source:
    repoURL: https://github.com/marcolam-sandboxvr/argocd-test.git
    targetRevision: main
    path: cluster
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    retry: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
