apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    fake:
      data:
        - key: test
          value: hi
