name: test push
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - id: generate-github-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.TEST_GITHUB_APP_ID }}
          private_key: ${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-github-token.outputs.token }}
      - run: echo ${{github.ref }} > test.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci skip] test: push'
